# Generated by Django 4.2.6 on 2023-10-05 15:14

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0001_initial'),
        ('Doctor', '0002_remove_doctor_doctorid_doctor_shifttype_and_more'),
        ('Diagnosis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosis',
            name='dateCreated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='description',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='diagnosisName',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='doctorID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Doctor.doctor'),
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='patientID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Patient.patient'),
        ),
    ]
